version: 0.2
env:
  secrets-manager:
    LOGIN: sonar:sonartoken
    HOST: sonar:HOST
    Organization: sonar:Organization
    Project: sonar:Project
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "Installing OpenJDK..."
      - yum install -y java-11-openjdk-devel
      - echo "Downloading and setting up SonarQube Scanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip
      - mv sonar-scanner-4.8.0.2856-linux sonar-scanner
      # Remove bundled JRE to ensure system Java is used
      - rm -rf sonar-scanner/jre
      - echo "Setting JAVA_HOME and updating PATH..."
      - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      - export PATH=$JAVA_HOME/bin:$PWD/sonar-scanner/bin:$PATH
      - echo "Verifying Java installation..."
      - java -version
      - echo "Verifying Sonar Scanner installation..."
      - sonar-scanner -v
  build:
    commands:
      - echo "Running SonarQube Scanner..."
      - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      - export PATH=$JAVA_HOME/bin:$PWD/sonar-scanner/bin:$PATH
      - sonar-scanner \
          -Dsonar.projectKey=$Project \
          -Dsonar.organization=$Organization \
          -Dsonar.host.url=$HOST \
          -Dsonar.login=$LOGIN
      - echo "Fetching SonarQube Quality Gate Status..."
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project > result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          echo "SonarQube Quality Gate failed."
          exit 1
        else
          echo "SonarQube Quality Gate passed."
        fi
artifacts:
  files:
    - result.json
  discard-paths: no
