# Generated by Django 4.2.16 on 2024-10-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
