# Generated by Django 4.2.16 on 2024-11-12 18:31
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0008_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='media/user_images/'),
        ),
    ]
