# Generated by Django 4.2.16 on 2024-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0009_alter_userimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='alert_sent',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='budget',
            name='monthly_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='weekly_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
