# Generated by Django 4.2.16 on 2024-11-12 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0010_remove_budget_alert_sent_remove_budget_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
