# Generated by Django 4.2.16 on 2024-11-12 21:49
# pylint: skip-file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0011_budget_alert_sent_budget_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='monthly_goal',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='weekly_goal',
        ),
    ]
